class Memoria{
    elements=[
        {
            element:"RedBull",
            source:"https://upload.wikimedia.org/wikipedia/de/c/c4/Red_Bull_Racing_logo.svg"
        },
        {
            element:"McLaren",
            source:"https://upload.wikimedia.org/wikipedia/en/6/66/McLaren_Racing_logo.svg"
        },
        {
            element:"Alpine",
            source:"https://upload.wikimedia.org/wikipedia/fr/b/b7/Alpine_F1_Team_2021_Logo.svg"
        },
        {
            element:"AstonMartin",
            source:"https://upload.wikimedia.org/wikipedia/fr/7/72/Aston_Martin_Aramco_Cognizant_F1.svg"
        },
        {
            element:"Ferrari",
            source:"https://upload.wikimedia.org/wikipedia/de/c/c0/Scuderia_Ferrari_Logo.svg"
        },
        {
            element:"Mercedes",
            source:"https://upload.wikimedia.org/wikipedia/commons/f/fb/Mercedes_AMG_Petronas_F1_Logo.svg"
        }
    ]
    constructor(hasFlippedCard,lockBoard,firstCard,secondCard){
        hasFlippedCard=false;
        lockBoard=false;
        firstCard=null;
        secondCard=null;
    }
    shuffleElements(){
        elementsBarajados=this.elements;
        for(i=this.elements.length - 1;i>0;i--){
            j=Math.floor(Math.random() * (i + 1));
            [elementsBarajados[i],elementsBarajados[j]]=[elementsBarajados[j],elementsBarajados[i]];
        }
        this.elements=elementosBarajados;
    }
    unflipCards(){
        setTimeout(,2000)
    }
    resetBoard(){
        hasFlippedCard=false;
        lockBoard=false;
        firstCard=null;
        secondCard=null;
    }
    checkForMatch(){

    }
    disableCards(){
        datastate=revealed;
        this.resetBoard();
    }
}